[package]
name = "terminaste-integration-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
publish = false

[dependencies]
crossbeam-channel.workspace = true
terminaste-pty = { path = "../terminaste-pty", version = "0.2.0" }
terminaste-settings = { path = "../terminaste-settings", version = "0.2.0" }
terminaste-ui = { path = "../terminaste-ui", version = "0.2.0" }
